---
- name: Set up ipxe server
  hosts: all
  become: no

  tasks:
    - name: Compile server
      delegate_to: 127.0.0.1
      vars:
        CGO_ENABLED: 0
      command: "go build ../../server.go"

    - name: Copy ipxe_server systemd service
      copy:
        src: ./templates/ipxe_server.service
        dest: /etc/systemd/system
        mode: u=rx

    - name: Copy server from local to remote
      copy:
        src: server
        dest: /usr/local/bin/ipxe_server

    - name: Enable ipxe_server service
      systemd:
        name: ipxe_server
        enabled: yes
        state: started
